name: Create Release Asset

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows,ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          # Replace 'source-folder' with the name of the folder you want to zip
          zip -r release-asset.zip NukeTabZ

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          body: |
            Description of the release.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NukeTabZ.zip
          asset_name: NukeTabZ.zip
          asset_content_type: application/zip
